# Generated by Django 4.2.14 on 2024-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(default=1085575072, max_length=50, verbose_name='телеграм chat-id'),
            preserve_default=False,
        ),
    ]
