# Generated by Django 4.2.14 on 2024-07-11 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "behavior",
                    models.CharField(
                        db_comment="действие, которое представляет собой привычка",
                        max_length=200,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_comment="время, когда необходимо выполнять привычку",
                        verbose_name="Время",
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Место")),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "ежедневно"),
                            ("once_a_week", "раз в неделю"),
                        ],
                        db_comment="периодичность выполнения привычки для напоминания в днях",
                        default="ежедневно",
                        null=True,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.DateTimeField(
                        blank=True,
                        db_comment="время, которое предположительно потратит пользователь на выполнение привычки",
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ("is_pleasant_habit", "is_public"),
            },
        ),
    ]
