# Generated by Django 4.2.14 on 2024-07-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="time",
        ),
    ]
