# Generated by Django 4.2.14 on 2024-07-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_remove_habit_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                db_comment="дата старта и время, когда необходимо выполнять привычку",
                default="2024-06-26 09:05:52.256402+05",
                verbose_name="Время",
            ),
            preserve_default=False,
        ),
    ]
